// ── Isolation Server (Phase 3 full implementation) ────────────────────────────
// Serves `/__om_isolation__` wrapper pages that render a single component in
// isolation (component artboard type).
//
// The proxy delegates all /__om_isolation__ requests here.
//
// Behaviour differs by framework (spec Phase 3 §3.5):
//
//   Vite:    Generate an inline HTML page with a `<script type="module">` that
//            imports the component from the Vite dev server and renders it via
//            ReactDOM.createRoot + window.__OM_ISO_RENDER__. No project changes.
//
//   Next.js: Next.js cannot serve arbitrary source modules. The CLI writes a
//            temporary page.tsx to `{appDir}/__om_isolation__/page.tsx` (App
//            Router) or `pages/__om_isolation__.tsx` (Pages Router). Next.js
//            compiles and hot-reloads it like any other page. The file is deleted
//            on CLI exit (process.on('exit') + SIGINT/SIGTERM).
//
// Query params on /__om_isolation__:
//   component  — exported symbol name, e.g. "DashboardCard"
//   file       — workspace-relative source path, e.g. "src/components/DashboardCard.tsx"
//
// spec: SOURCE-AWARE-CANVAS.md Phase 3 §3.5 "Component Isolation"

import {
  existsSync, mkdirSync, writeFileSync, readFileSync, rmSync, realpathSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import type { IncomingMessage, ServerResponse } from 'node:http';
import { detectFramework } from './detect-framework.js';

// ── Config ────────────────────────────────────────────────────────────────────

const ISOLATION_DIR_NAME   = '__om_isolation__';
const NEXT_PAGE_CONTENT    = (componentName: string, importPath: string, isDefault: boolean) => `\
'use client';
// AUTO-GENERATED by @originmain/cli — do not edit.
// This file is deleted when the CLI stops (process.on('exit')).
// Add __om_isolation__/ to your .gitignore to prevent accidental commits.
import ${isDefault ? componentName : `{ ${componentName} }`} from '${importPath}';
import { useEffect } from 'react';

// Expose render function for the host-to-iframe UPDATE_ISOLATION_PROPS protocol
function IsolationPage() {
  useEffect(() => {
    if (typeof window === 'undefined') return;
    window.__OM_ISO_RENDER__ = function() {
      // Force a re-render by dispatching a custom event — the component
      // reads window.__OM_ISO_PROPS__ in its own render cycle.
    };
    // Trigger initial render
    window.__OM_ISO_PROPS__ = window.__OM_ISO_PROPS__ || {};
  }, []);

  // Read props from the isolation protocol global
  const props = (typeof window !== 'undefined' && window.__OM_ISO_PROPS__) ? window.__OM_ISO_PROPS__ : {};
  return <${componentName} {...(props as Record<string, unknown>)} />;
}

export default IsolationPage;

// Type augmentation so TS doesn't complain about the globals
declare global {
  interface Window {
    __OM_ISO_PROPS__:   Record<string, unknown> | undefined;
    __OM_ISO_RENDER__:  (() => void) | undefined;
  }
}
`;

// The Vite inline HTML template renders the component via ReactDOM.createRoot
// and exposes window.__OM_ISO_RENDER__ for live prop updates from the host.
const VITE_HTML = (
  componentName: string,
  importPath: string,
  isDefault: boolean,
) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${componentName} — Isolation</title>
  <style>
    body { margin: 0; padding: 24px; box-sizing: border-box; }
    #root { display: contents; }
  </style>
</head>
<body>
  <div id="root"></div>
  <script type="module">
    // All Originmain globals use the __OM_ISO_ prefix to minimise collision risk.
    import ${isDefault ? componentName : `{ ${componentName} }`} from '${importPath}';
    import { createRoot } from 'react-dom/client';
    import React from 'react';

    if (typeof window.__OM_ISO_PROPS__ !== 'undefined') {
      console.warn('[Originmain] window.__OM_ISO_PROPS__ was already defined — possible name collision. Proceeding anyway.');
    }
    window.__OM_ISO_PROPS__ = window.__OM_ISO_PROPS__ || {};

    const _root = createRoot(document.getElementById('root'));

    window.__OM_ISO_RENDER__ = function() {
      _root.render(React.createElement(${componentName}, window.__OM_ISO_PROPS__ || {}));
    };

    window.__OM_ISO_RENDER__();
  </script>
</body>
</html>`;

// ── Temp file tracking ────────────────────────────────────────────────────────
// All temp files created by this module are tracked here so they can be deleted
// on process exit (including SIGINT / SIGTERM).

const tempFiles = new Set<string>();
let cleanupRegistered = false;

function deleteTempFile(filePath: string): void {
  try {
    if (existsSync(filePath)) rmSync(filePath, { recursive: true, force: true });
    // Also try to remove the parent dir if it's our isolation dir
    const parent = dirname(filePath);
    if (parent.endsWith(ISOLATION_DIR_NAME) && existsSync(parent)) {
      rmSync(parent, { recursive: true, force: true });
    }
  } catch { /* file may already be deleted */ }
  tempFiles.delete(filePath);
}

function registerCleanup(): void {
  if (cleanupRegistered) return;
  cleanupRegistered = true;

  const cleanup = () => {
    for (const f of tempFiles) deleteTempFile(f);
  };

  process.on('exit',   cleanup);
  process.on('SIGINT',  () => { cleanup(); process.exit(130); });
  process.on('SIGTERM', () => { cleanup(); process.exit(143); });
}

// ── Startup cleanup ───────────────────────────────────────────────────────────
// On CLI start, delete any pre-existing __om_isolation__ directories from a
// previous unclean exit (spec §3.5 "Startup cleanup").

export function cleanupIsolationDirs(projectRoot: string): void {
  const candidates = [
    join(projectRoot, 'src', 'app', ISOLATION_DIR_NAME),
    join(projectRoot, 'app',        ISOLATION_DIR_NAME),
    join(projectRoot, 'pages',      `${ISOLATION_DIR_NAME}.tsx`),
  ];
  for (const p of candidates) {
    if (existsSync(p)) {
      try { rmSync(p, { recursive: true, force: true }); } catch { /* ignore */ }
    }
  }
}

// ── .gitignore injection ──────────────────────────────────────────────────────

function ensureGitignore(projectRoot: string): void {
  const gitignorePath = join(projectRoot, '.gitignore');
  const entry = `\n# Originmain component isolation frame (auto-deleted on CLI stop)\n${ISOLATION_DIR_NAME}/\n`;
  try {
    const existing = existsSync(gitignorePath) ? readFileSync(gitignorePath, 'utf-8') : '';
    if (!existing.includes(ISOLATION_DIR_NAME)) {
      writeFileSync(gitignorePath, existing + entry, 'utf-8');
    }
  } catch { /* .gitignore is optional — no-op on error */ }
}

// ── Next.js page writer ───────────────────────────────────────────────────────

type NextPageLocation = { type: 'app'; dir: string } | { type: 'pages'; dir: string } | null;

function findNextPageLocation(projectRoot: string): NextPageLocation {
  const srcApp   = join(projectRoot, 'src', 'app');
  const rootApp  = join(projectRoot, 'app');
  const pages    = join(projectRoot, 'pages');

  if (existsSync(srcApp))  return { type: 'app', dir: srcApp };
  if (existsSync(rootApp)) return { type: 'app', dir: rootApp };
  if (existsSync(pages))   return { type: 'pages', dir: pages };
  return null;
}

function writeNextIsolationPage(
  projectRoot: string,
  componentName: string,
  importPath: string,
  isDefault: boolean,
): string {
  registerCleanup();
  ensureGitignore(projectRoot);

  const loc = findNextPageLocation(projectRoot);

  let filePath: string;
  if (!loc) {
    // No router found — fall through to Vite approach (caller handles this)
    throw new Error('no-next-router');
  } else if (loc.type === 'app') {
    const dir = join(loc.dir, ISOLATION_DIR_NAME);
    mkdirSync(dir, { recursive: true });
    filePath = join(dir, 'page.tsx');
  } else {
    filePath = join(loc.dir, `${ISOLATION_DIR_NAME}.tsx`);
  }

  const content = NEXT_PAGE_CONTENT(componentName, importPath, isDefault);
  writeFileSync(filePath, content, 'utf-8');
  tempFiles.add(filePath);
  return filePath;
}

// ── IsolationServer class ─────────────────────────────────────────────────────

interface IsolationServerOptions {
  projectRoot: string;
  /** Base URL of the running dev server, e.g. "http://localhost:3000" */
  devServerBase: string;
  /**
   * Optional: async function to look up whether a component is a default export.
   * If omitted, assumes named export (the safe default for most components).
   */
  resolveIsDefaultExport?: (componentName: string, filePath: string) => Promise<boolean>;
}

export class IsolationServer {
  private readonly projectRoot:  string;
  private readonly devServerBase: string;
  private readonly resolveIsDefault: NonNullable<IsolationServerOptions['resolveIsDefaultExport']>;
  private readonly framework: ReturnType<typeof detectFramework>;

  constructor(opts: IsolationServerOptions) {
    this.projectRoot   = opts.projectRoot;
    this.devServerBase = opts.devServerBase;
    this.framework     = detectFramework(opts.projectRoot);
    this.resolveIsDefault = opts.resolveIsDefaultExport ?? (() => Promise.resolve(false));
  }

  /** Call at startup to purge any leftover __om_isolation__ dirs. */
  cleanup(): void {
    cleanupIsolationDirs(this.projectRoot);
  }

  /** Handle an incoming /__om_isolation__?component=X&file=Y request. */
  async handleRequest(req: IncomingMessage, res: ServerResponse): Promise<void> {
    const urlStr = req.url ?? '/';
    const url    = new URL(urlStr, 'http://localhost');

    const componentName = url.searchParams.get('component') ?? '';
    const filePath      = url.searchParams.get('file')      ?? '';

    if (!componentName || !filePath) {
      this.sendError(res, 400, 'Missing required query params: component, file');
      return;
    }

    // Security: reject path traversal attempts in the file param
    const resolvedFile = join(this.projectRoot, filePath);
    try {
      const real = realpathSync(resolvedFile);
      if (!real.startsWith(realpathSync(this.projectRoot))) {
        this.sendError(res, 403, 'Path traversal not allowed');
        return;
      }
    } catch {
      // File may not exist yet — that's OK, the import will fail at runtime
    }

    const isDefault = await this.resolveIsDefault(componentName, filePath);

    if (this.framework === 'next') {
      await this.handleNextJs(req, res, componentName, filePath, isDefault);
    } else {
      this.handleVite(res, componentName, filePath, isDefault);
    }
  }

  // ── Vite handler ──────────────────────────────────────────────────────────

  private handleVite(
    res: ServerResponse,
    componentName: string,
    filePath: string,
    isDefault: boolean,
  ): void {
    // Import path: use the file param as a root-relative path (Vite serves from root)
    const importPath = filePath.startsWith('/') ? filePath : `/${filePath}`;
    const html = VITE_HTML(componentName, importPath, isDefault);
    res.writeHead(200, {
      'content-type':  'text/html; charset=utf-8',
      'cache-control': 'no-store',
    });
    res.end(html);
  }

  // ── Next.js handler ───────────────────────────────────────────────────────

  private async handleNextJs(
    req: IncomingMessage,
    res: ServerResponse,
    componentName: string,
    filePath: string,
    isDefault: boolean,
  ): Promise<void> {
    // Build an import path relative to the isolation page location.
    // The temp page lives in {appDir}/__om_isolation__/page.tsx, so the
    // component's import path is relative from there.
    // We use an absolute-from-root import (/@/... or relative to src/) that
    // Next.js resolves via tsconfig paths — or we use a relative path.
    // The simplest approach: use a root-relative path prefixed with '@/' if
    // the project uses the common Next.js path alias, or a relative path otherwise.
    const importPath = filePath.replace(/^src\//, '@/');

    try {
      writeNextIsolationPage(this.projectRoot, componentName, importPath, isDefault);
    } catch (err) {
      if (err instanceof Error && err.message === 'no-next-router') {
        // Fall back to Vite-style inline HTML
        this.handleVite(res, componentName, filePath, isDefault);
        return;
      }
      this.sendError(res, 500, `Failed to write isolation page: ${err instanceof Error ? err.message : String(err)}`);
      return;
    }

    // Redirect to the temp Next.js page so the browser fetches the compiled page.
    const target = `${this.devServerBase}/${ISOLATION_DIR_NAME}?component=${encodeURIComponent(componentName)}&file=${encodeURIComponent(filePath)}`;
    res.writeHead(302, { Location: target, 'cache-control': 'no-store' });
    res.end();
  }

  private sendError(res: ServerResponse, status: number, message: string): void {
    res.writeHead(status, { 'content-type': 'text/plain; charset=utf-8' });
    res.end(`Originmain Isolation Error: ${message}`);
  }
}

// ── Legacy function-style entry point (for proxy.ts compatibility) ─────────────
// The proxy.ts currently calls handleIsolationRequest(req, res) from a module-level
// IsolationServer instance. Export a convenience function that delegates to a
// default instance configured from environment variables.

let _defaultServer: IsolationServer | null = null;

export function initIsolationServer(opts: IsolationServerOptions): void {
  _defaultServer = new IsolationServer(opts);
  _defaultServer.cleanup(); // startup cleanup
}

/** Handles any request to /__om_isolation__/* using the initialised server. */
export async function handleIsolationRequest(
  req: IncomingMessage,
  res: ServerResponse,
): Promise<void> {
  if (!_defaultServer) {
    // Not yet initialised — return the stub response
    res.writeHead(503, { 'content-type': 'text/html; charset=utf-8' });
    res.end('<body style="font:13px monospace;padding:24px">Isolation server not initialised — call initIsolationServer() first.</body>');
    return;
  }
  return _defaultServer.handleRequest(req, res);
}
